databases:
  - name: backendCalculoNotas

services:
  - type: web
    name: backendCalculoNotas
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: SECRET_KEY_BASE
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: backendCalculoNotas
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false